[package]
name = "tree-calc"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]

[features]
v0-1 = []
v1-0 = ["v0-1"]

[lib]
name = "treecalc"
path = "src/lib.rs"

[[bin]]
name = "tree-calc-repl"
path = "src/bin.rs"

[dependencies]
regex = "*"
rand = "0.6.0"
